version: '3.5'

services:

  db:
    image: postgres:15.2
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    environment:

     POSTGRES_USER: root
     POSTGRES_DB: CRM
     POSTGRES_PASSWORD: password
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge


